mikronik/apps/monitor/urls.py
from django.urls import path
from . import views

app_name = 'monitor'

urlpatterns = [
	path('', views.index, name = 'index'),
	path('all_device/', views.all_device, name = 'all_device'),
	path('group/', views.group, name = 'group'),
	path('invent/', views.invent, name = 'invent'),
	path('invent/nb', views.invent, name = 'inventNB'),
	path('invent/pc', views.invent, name = 'inventPC'),
	path('group/group_command', views.group_command, name = 'group_command'),
	path('all_device/sort_all_device', views.sort_all_device, name = 'sort_all_device'),
	path('all_device/save_device', views.save_device, name = 'save_device'),
	path('<int:mikrot_id>/', views.detail, name = 'detail'),
	path('<int:mikrot_id>/view_host/', views.view_host, name = 'view_host'),
	path('<int:mikrot_id>/sort_host/', views.sort_host, name = 'sort_host')
] 

mikronik/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('monitor.urls')),
    path('monitor/', include('monitor.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

mikronik/apps/monitor/models.py
from django.db import models


class Mikrot(models.Model):
	mikrotIP = models.CharField("Адрес Микротик", max_length = 20)
	mikrotName = models.CharField("Имя Микротик", max_length =  30)
	mikrotLogin = models.CharField("Логин Микротик", max_length =  30)
	mikrotPass = models.CharField("Пароль Микротик", max_length = 30)

	def __str__(self):
		return self.mikrotName

	class Meta():
		verbose_name = 'Микротик'
		verbose_name_plural = 'Микротики'



class InventPC(models.Model):
	hostNamePC = models.CharField(max_length = 20)
	userPC = models.CharField(max_length = 50)
	motherBandPC = models.CharField(max_length = 50)
	hardDrivePC = models.CharField(max_length = 20)
	ramPC = models.CharField(max_length = 20)
	processorPC = models.CharField(max_length = 50)
	placePC = models.CharField(max_length = 20)
	dateInvent = models.CharField(max_length = 20)

	def __str__(self):
		return self.hostNamePC
	
class InventNote(models.Model):
	hostNameNote = models.CharField(max_length = 20)
	userNote = models.CharField(max_length = 50)
	modelNote = models.CharField(max_length = 50)
	hardDriveNote = models.CharField(max_length = 20)
	ramNote = models.CharField(max_length = 20)
	processorNote = models.CharField(max_length = 50)
	placeNote = models.CharField(max_length = 20)
	dateInvent = models.CharField(max_length = 20)

	def __str__(self):
		return self.hostNameNote

class InventPrinter(models.Model):
	hostNamePrinter = models.CharField(max_length = 20)
	modelPrinter = models.CharField(max_length = 50)
	tonerTypePrinter = models.CharField(max_length = 20)
	placePrinter = models.CharField(max_length = 20)
	dateInvent = models.CharField(max_length = 20)

	def __str__(self):
		return self.hostNamePrinter

mikronik/apps/monitor/views.py
from django.shortcuts import render
from .models import Mikrot, InventPrinter, InventPC, InventNote
from django.http import Http404, HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from . import mikropi
import pandas as pd
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.files import File

api = mikropi.newMikrotApi()
	
def invent(request):
	try:
		deviceHost = request.POST['device']

		listDev = api.viewAllHost()
		
		
	
		
		if deviceHost == '1':
			listNote = InventNote.objects.all()
			listDeviceNote = []
			for note in listNote:
				arr = []
				
				arr.append(note.hostNameNote)
				arr.append(note.userNote)
				arr.append(note.modelNote)
				arr.append(note.hardDriveNote)
				arr.append(note.ramNote)
				arr.append(note.processorNote)
				arr.append(note.placeNote)
				arr.append(note.dateInvent)
				listDeviceNote.append(arr)
				arr = []
			
			return render(request, 'monitor/nb.html', {'listDevice': listDeviceNote})

		if deviceHost == '5':
			listPC = InventPC.objects.all()
			listDevicePC = []
			for note in listPC:
				arr = []
			
				arr.append(note.hostNamePC)
				arr.append(note.userPC)
				arr.append(note.motherBandPC)
				arr.append(note.hardDrivePC)
				arr.append(note.ramPC)
				arr.append(note.processorPC)
				arr.append(note.placePC)
				arr.append(note.dateInvent)
				listDevicePC.append(arr)
				arr = []
			

			return render(request, 'monitor/pc.html', {'listDevice': listDevicePC})

		if deviceHost == '2':
			print('pr')
			listDevice = api.parsePrinters(deviceHost, listDev)
			return render(request, 'monitor/invent.html', {'listDevice': listDevice})
		

		

	except:
		listDev = '|'
		return render(request, 'monitor/invent.html', {'listDevice': listDev})

	return render(request, 'monitor/invent.html', {'listDevice': listDevice})




@permission_required('mikronik.index')
def index(request):
	arrM = api.viewListMikrot()

	return render(request, 'monitor/list.html', {'arr': arrM})

@permission_required('mikronik.detail')
def detail(request, mikrot_id):
	listDevice = api.viewAllDevice(mikrot_id) 
	name = api.viewHostName(mikrot_id)		
	try:
		a = Mikrot.objects.get(id = mikrot_id)
		
	except:
		raise Http404("Узел не найден")

	return render(request, 'monitor/detail.html', {'mikrot': a, 'hostname': name, 'listDevice':listDevice})


@permission_required('mikronik.index')
def view_host(request, mikrot_id):
	try:
		a = Mikrot.objects.get(id = mikrot_id)
		
	except:
		raise Http404("Узел не найден")

	cmd =  request.POST['command']
	name = api.viewHostName(mikrot_id)
	listDevice = api.viewAllDevice(mikrot_id)
	resCommand = ''
	if cmd:
		resCommand = api.cmdExecution(cmd, mikrot_id)

		for res in resCommand:
			for r in res:
				print(r)
			print('-----------------')

	return render(request, 'monitor/detail.html', {'mikrot': a, 'hostname': name, 'listDevice':listDevice, 'result': resCommand})

@permission_required('mikronik.index')
def sort_host(request, mikrot_id):

	try:
		a = Mikrot.objects.get(id = mikrot_id)
		
	except:
		raise Http404("Узел не найден")

	deviceHost = request.POST['device']


	name = api.viewHostName(mikrot_id)
	listDevice = api.changeDevice(deviceHost, api.viewAllDevice(mikrot_id))

	return render(request, 'monitor/detail.html', {'mikrot': a, 'hostname': name, 'listDevice':listDevice})



def all_device(request):

	listDev = api.viewAllHost()
	return render(request, 'monitor/all_device.html', {'listDevice': listDev})


def sort_all_device(request):

	try:
		deviceHost = request.POST['device']

		listDev = api.viewAllHost()

		listDevice = api.changeDevice(deviceHost, listDev)
		

		return render(request, 'monitor/all_device.html', {'listDevice': listDevice})
	except:
		listDev = api.viewAllHost()
		return render(request, 'monitor/all_device.html', {'listDevice': listDev})


def save_device(request):
	deviceHost = request.POST['device']

	listDev = api.viewAllHost()

	listDevice = api.changeDevice(deviceHost, listDev)
	api.saveDevice(listDevice, deviceHost)
	return render(request, 'monitor/all_device.html', {'listDevice': listDevice})





def invent_printers(request):
	try:
		deviceHost = request.POST['device']

		listDev = api.viewAllHost()

		listDevice = api.changeDevice(deviceHost, listDev)

		return render(request, 'monitor/invent.html', {'listDevice': listDevice})

	except:
		listDev = api.viewAllHost()
		return render(request, 'monitor/invent.html', {'listDevice': listDev})

	return render(request, 'monitor/invent.html', {'listDevice': listDevice})



@permission_required('mikronik.index')
def group(request):

	all_mikrot = api.viewListMikrotGroup()

	
	return render(request, 'monitor/group.html', {'all_mikrot': all_mikrot})

@permission_required('mikronik.index')
def group_command(request):
	groupCommand = ''
	allM = Mikrot.objects.all()
	all_mikrot = api.viewListMikrotGroup()

	arrMain = []

	groupCommand =  request.POST['command']
	groupDevice = []
	
	for a in allM:
			
		statusDevice = request.POST.get(str(a.id), False)
			
		arrMain.append(a.id)
		arrMain.append(statusDevice)

		groupDevice.append(arrMain)
		arrMain = []

	api.groupCommand(groupCommand, groupDevice)

	
	return render(request, 'monitor/group.html', {'all_mikrot': all_mikrot})

mikronik/templates/base.html
<!DOCTYPE html>

<html lang = "en">
	<head>
		<meta charset="utf-8">

		 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
		<title>{% block title %} Mikronik {% endblock %}</title>

	</head>
	<body>

			
		<header style="background-color: whitesmoke; width: 100%" class="d-flex justify-content-center py-3">
      <ul class="nav nav-pills">
      	<li style="font-size: 150%" class="nav-link">{{hostname}}</li>
      	<li style="font-size: 150%" class="nav-link"><a style="cursor: pointer; text-decoration: none;" target="_blank" href="http:\\{{mikrot.mikrotIP}}">{{mikrot.mikrotIP}}</a></li>
        <li class="nav-item"><a href="/admin" class="nav-link active" aria-current="page">Admin</a></li>
        <li class="nav-item"><a href="/monitor" class="nav-link">Главная</a></li>
        <li class="nav-item"><a href="/all_device" class="nav-link">Устройства</a></li>
        <li class="nav-item"><a href="/monitor/group" class="nav-link">Групповое управление</a></li>
      	<li class="nav-item"><a href="/monitor/invent" class="nav-link">Инвентаризация</a></li>
      	
      {% if user.is_authenticated %}
     <li class="nav-link">{{ user.get_username }}</li>
     <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
   {% else %}
     <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
   {% endif %} 
      </ul>

    </header>

		<!--<header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-4">Simple header</span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="#" class="nav-link active" aria-current="page">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Features</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Pricing</a></li>
        <li class="nav-item"><a href="#" class="nav-link">FAQs</a></li>
        <li class="nav-item"><a href="#" class="nav-link">About</a></li>
      </ul>
    </header>-->

		
		{% block content %}

		{% endblock %}

	</body>

</html>

mikronik/templates/monitor/all_device.html
{% extends 'base.html' %}

{% block title %}Mikronik{% endblock %}



{% block content %}
<script type="text/javascript">
function saveDev(){
	
	
    var form = document.getElementById("saveFindForm");
    form.action = "{% url 'monitor:save_device' %}";
    form.submit();
}


function findDev(){
	
	
    var form = document.getElementById("saveFindForm");
    form.action = "{% url 'monitor:sort_all_device' %}";
    form.submit();
}

</script>

<nav class="navbar navbar-expand navbar-dark bg-white" aria-label="Second navbar example">
    <div class="container-fluid ">
      
      <div class="collapse navbar-collapse " id="navbarsExample02">
        <ul class="navbar-nav me-auto">
       
        </ul>

       

        <form id = "saveFindForm" method="POST">
					{% csrf_token %}

					

					<div class="d-flex w-100 gap-2">
						
					
					<select name="device" style="width: 200px;" class="form-select" aria-label="Default select example" >
					  <option value="0" >Все</option>
					  <option value="1" >Ноутбуки</option>
					  <option value="2" >Принтеры</option>
					  <option value="3" >Базы</option>
					  <option value="5" >Системники</option>
					  <option value="4" >Неизвестно</option>
					</select>
					
					
					
					<input id = 'findBtn' onclick="findDev()" name="find" type="submit" value="Поиск" class="btn btn-primary">
					<input id = 'saveBtn' onclick="saveDev()" name="save" type="submit" value="Сохранить" class="btn btn-primary">
					</div>
				</form>
				
					
			</div>
		</div>
</nav>




<table style="width: 100%; float: left; top: 14%" class="table table-striped">
	  <thead>
	    <tr>
	    
	      <th scope="col">IP</th>
	      <th scope="col">Hostname</th>
	      <th scope="col">MAC</th>
	      <th scope="col">Объект</th>
	      <th scope="col">Устройство</th>
	    </tr>
	  </thead>
	  <tbody>
	
	  	{% for device in listDevice %}
	  	
	    <tr>
	 
	      <td>{{device.0}}</td>
	      <td>{{device.2}}</td>
	      <td>{{device.1}}</td>
	      <td>{{device.4}}</td>
	      {% if device.3 == "Телефонная База" or  device.3 == "Принтер" %}
	      <td><a style="cursor: pointer;" target="_blank" href="http:\\{{device.0}}">{{device.3}}</a></td>
	      {% else %}
	      <td>{{device.3}}</td>

	      {% endif %}
	    </tr>
	 
	   	{% endfor %}
	  </tbody>
</table>




{% endblock %}

mikronik/templates/monitor/detail.html
{% extends 'base.html' %}

{% block title %}{{mikrot.mikrotName}}{% endblock %}

{% block content %}





<form action="{% url 'monitor:view_host' mikrot.id %}" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<div class="form-group mx-sm-3 mb-2">
			<input style="position: absolute ; width: 69%; top: 10%;" type="text" name="command" placeholder="Введите команду" class="form-control">
		</div>

	<input style="position: absolute ; right: 24%; top: 10%;" type="submit" value="Отправить" class="btn btn-primary mb-2">
	</div>

</form>


<div >
<form action="{% url 'monitor:sort_host' mikrot.id %}" method="POST">
	{% csrf_token %}
<select name="device" style="position: absolute; right: 8%; width: 300px; top: 10%;" class="form-select" aria-label="Default select example">
  <option value="0">Все</option>
  <option value="1">Ноутбуки</option>
  <option value="2">Принтеры</option>
  <option value="3">Базы</option>
  <option value="5">Системники</option>
  <option value="4">Неизвестно</option>
</select>
<input style="position: absolute ; right: .5%; width:  130px;top: 10%;" type="submit" value="Поиск" class="btn btn-primary">
<form>
</div>






<table style="width: 100%;position: absolute; float: left; top: 14%" class="table table-striped table-hover">
	  <thead>
	    <tr>
	    
	      <th scope="col">IP</th>
	      <th scope="col">Hostname</th>
	      <th scope="col">MAC</th>
	      <th scope="col">Устройство</th>
	    </tr>
	  </thead>
	  <tbody>
	
	  	{% for device in listDevice %}
	  	
	    <tr>
	 
	      <td>{{device.0}}</td>
	      <td>{{device.2}}</td>
	      <td>{{device.1}}</td>
	      {% if device.3 == "Телефонная База" or  device.3 == "Принтер" %}
	      <td><a style="cursor: pointer;" target="_blank" href="http:\\{{device.0}}">{{device.3}}</a></td>
	      {% else %}
	      <td>{{device.3}}</td>

	      {% endif %}
	    </tr>
	 
	   	{% endfor %}
	  </tbody>
</table>

{% endblock %}

mikronik/templates/monitor/group.html
{% extends 'base.html' %}

{% block title %}Mikronik{% endblock %}
{{all_mikrot}}

{% block content %}

	<form action="{% url 'monitor:group_command' %}" method="POST">
	{% csrf_token %}
	<div class="form-group">
		<div class="form-group mx-sm-3 ">
			<input style="position: absolute ; width: 93%; top: 10%;" type="text" name="command" placeholder="Введите команду" class="form-control">
		</div>

	<input style="position: absolute ; right: .5%; top: 10%;" type="submit" value="Отправить" class="btn btn-primary mb-2">
	</div>
	
	

	<table style="width: 100%;position: absolute;top: 15%" class="table table-striped">
	  <thead>
	    <tr>
	    <th scope="col">#</th>
	      <th scope="col">Hostname</th>
	      <th scope="col">IP</th>
	      <th scope="col" class="input" style="cursor: pointer;">Change All</th>
	    </tr>
	  </thead>
	  <tbody>
	
	  	{% for i in all_mikrot %}
	  	
	    <tr>
	 
	      <th scope="row">{{i.0}}</th>
	      <th scope="row"><a style="cursor: pointer;" href="{% url 'monitor:detail' i.3 %}">{{i.1}}</a></th>
	      <th scope="row">{{i.2}}</th>
	      <th scope="row"><input class="checkbox-input"  name = "{{i.3}}" type="checkbox"></th>
	    </tr>
	 
	   	{% endfor %}
	  </tbody>
	
	  	<script type="text/javascript">

	  			

				let input = document.querySelector(".input"),
				checkboxInput = document.querySelectorAll(".checkbox-input");
				
				input.addEventListener("click", function (){

				  for(let i = 0; i < checkboxInput.length; i++) {

				    if(checkboxInput[i].checked)
				    {
				    	
				      checkboxInput[i].removeAttribute("checked");
				    } 

				    else 
				    {
				      checkboxInput[i].setAttribute("checked", "checked");
				    }
				  }
				});

				

				
	</script>
</form>
	
{% endblock %}

mikronik/templates/monitor/invent.html
{% extends 'base.html' %}

{% block title %}Инвентаризация{% endblock %}


{% load static %}

{% block content %}



  
<script type="text/javascript">
function saveDev(){
  
  
    var form = document.getElementById("saveFindForm");
    form.action = "{% url 'monitor:save_device' %}";
    form.submit();
}


function findDev(){
  
  
    var form = document.getElementById("saveFindForm");
    form.action = "{% url 'monitor:invent' %}";
    form.submit();
}

</script>

<nav class="navbar navbar-expand navbar-dark bg-white" aria-label="Second navbar example">
    <div class="container-fluid ">
      
      <div class="collapse navbar-collapse " id="navbarsExample02">
        <ul class="navbar-nav me-auto">
       
        </ul>

       

        <form id = "saveFindForm" method="POST">
          {% csrf_token %}

          

          <div class="d-flex w-100 gap-2">
            
          
          <select name="device" style="width: 200px;" class="form-select" aria-label="Default select example" >
            
            <option value="1" >Ноутбуки</option>
            <option value="2" >Принтеры</option>
            <option value="5" >Системники</option>
           
          </select>
          
          
          
          <input id = 'findBtn' onclick="findDev()" name="find" type="submit" value="Поиск" class="btn btn-primary">
          <!--<input id = 'saveBtn' onclick="saveDev()" name="save" type="submit" value="Сохранить" class="btn btn-primary">-->
          </div>
        </form>
        
          
      </div>
    </div>
</nav>



<table style="width: 100%; float: left; top: 14%" class="table table-striped table-hover">
    <thead>
      <tr>
      
        <th scope="col">IP</th>
        <th scope="col">Hostname</th>
        <th scope="col">Model</th>
        <th scope="col">Toner type</th>
        <th scope="col">Toner level</th>
        <th scope="col">Объект</th>
        <th scope="col">Устройство</th>
      </tr>
    </thead>
    <tbody>
  
      {% for device in listDevice %}
      
      <tr>
   
        <td>{{device.0}}</td>
        <td>{{device.2}}</td>
        <td>{{device.5}}</td>
        <td>{{device.6}}</td>

        {% if device.7 <= 10 %}
        <td style="color: red;">{{device.7}}%</td>

        {% elif device.7 > 20 %}
        <td style="color: green;">{{device.7}}%</td>

        {% elif device.7 > 10 and device.7 <= 20 %}
        <td style="color: #FFA500;">{{device.7}}%</td>


        {% else %}
        <td >{{device.7}}</td>

        {% endif %}

        <td>{{device.4}}</td>
        
  
        <td><a style="cursor: pointer;" target="_blank" href="http:\\{{device.0}}">{{device.3}}</a></td>
       
      </tr>
   
      {% endfor %}
    </tbody>
</table>


{% endblock %}

mikronik/templates/monitor/list.html
{% extends 'base.html' %}

{% block title %}Mikronik{% endblock %}
{{all_mikrot}}

{% block content %}

	<table style="width: 100%; float:left;" class="table table-striped table-hover">
	  <thead>
	    <tr>
	      <th scope="col">#</th>
		  <th scope="col">Объект</th>
	      <th scope="col">IP</th>
	      <th scope="col">Доступность</th>
	    </tr>
	  </thead>
	  <tbody>
	
	  	{% for i in arr %}
	  	
	  	
	    <tr>
	    	
	      <th scope="row">{{i.0}}</th>
	      <th scope="row"><a style="cursor: pointer;" href="{% url 'monitor:detail' i.4 %}">{{i.1}}</a></th>
	      <th scope="row">{{i.2}}</th>

	      {% if i.3 == 'Available' %}
	      		<td style="color: green;">{{i.3}}</td>

	      	{% else %}

	      		<td style="color: red;">{{i.3}}</td>
	    	{% endif %}
	    
	    </tr>
	
	 	
	   	{% endfor %}
	  </tbody>
	</table>



	
{% endblock %}

mikronik/templates/monitor/mn.html
{% extends 'base.html' %}

{% block title %}Mikronik{% endblock %}



{% block content %}
<script type="text/javascript">
function saveDev(){
	
	
    var form = document.getElementById("saveFindForm");
    form.action = "{% url 'monitor:save_device' %}";
    form.submit();
}


function findDev(){
	
	
    var form = document.getElementById("saveFindForm");
    form.action = "{% url 'monitor:sort_all_device' %}";
    form.submit();
}

</script>

<nav class="navbar navbar-expand navbar-dark bg-white" aria-label="Second navbar example">
    <div class="container-fluid ">
      
      <div class="collapse navbar-collapse " id="navbarsExample02">
        <ul class="navbar-nav me-auto">
       
        </ul>

       

        <form id = "saveFindForm" method="POST">
					{% csrf_token %}

					

					<div class="d-flex w-100 gap-2">
						
					
					<select name="device" style="width: 200px;" class="form-select" aria-label="Default select example" >
					  <option value="0" >Все</option>
					  <option value="1" >Ноутбуки</option>
					  <option value="2" >Принтеры</option>
					  <option value="3" >Базы</option>
					  <option value="5" >Системники</option>
					  <option value="4" >Неизвестно</option>
					</select>
					
					
					
					<input id = 'findBtn' onclick="findDev()" name="find" type="submit" value="Поиск" class="btn btn-primary">
					<input id = 'saveBtn' onclick="saveDev()" name="save" type="submit" value="Сохранить" class="btn btn-primary">
					</div>
				</form>
				
					
			</div>
		</div>
</nav>




<table style="width: 100%; float: left; top: 14%" class="table table-striped table-hover">
	  <thead>
	    <tr>
	    
	      <th scope="col">IP</th>
	      <th scope="col">Hostname</th>
	      <th scope="col">MAC</th>
	      <th scope="col">Объект</th>
	      <th scope="col">Устройство</th>
	    </tr>
	  </thead>
	  <tbody>
	
	  	{% for device in listDevice %}
	  	
	    <tr>
	 
	      <td>{{device.0}}</td>
	      <td>{{device.2}}</td>
	      <td>{{device.1}}</td>
	      <td>{{device.4}}</td>
	      {% if device.3 == "Телефонная База" or  device.3 == "Принтер" %}
	      <td><a style="cursor: pointer;" target="_blank" href="http:\\{{device.0}}">{{device.3}}</a></td>
	      {% else %}
	      <td>{{device.3}}</td>

	      {% endif %}
	    </tr>
	 
	   	{% endfor %}
	  </tbody>
</table>




{% endblock %}

mikronik/templates/monitor/pr.html
{% extends 'base.html' %}

{% block title %}Mikronik{% endblock %}



{% block content %}
<script type="text/javascript">
function saveDev(){
	
	
    var form = document.getElementById("saveFindForm");
    form.action = "{% url 'monitor:save_device' %}";
    form.submit();
}


function findDev(){
	
	
    var form = document.getElementById("saveFindForm");
    form.action = "{% url 'monitor:sort_all_device' %}";
    form.submit();
}

</script>

<nav class="navbar navbar-expand navbar-dark bg-white" aria-label="Second navbar example">
    <div class="container-fluid ">
      
      <div class="collapse navbar-collapse " id="navbarsExample02">
        <ul class="navbar-nav me-auto">
       
        </ul>

       

        <form id = "saveFindForm" method="POST">
					{% csrf_token %}

					

					<div class="d-flex w-100 gap-2">
						
					
					<select name="device" style="width: 200px;" class="form-select" aria-label="Default select example" >
					  <option value="0" >Все</option>
					  <option value="1" >Ноутбуки</option>
					  <option value="2" >Принтеры</option>
					  <option value="3" >Базы</option>
					  <option value="5" >Системники</option>
					  <option value="4" >Неизвестно</option>
					</select>
					
					
					
					<input id = 'findBtn' onclick="findDev()" name="find" type="submit" value="Поиск" class="btn btn-primary">
					<input id = 'saveBtn' onclick="saveDev()" name="save" type="submit" value="Сохранить" class="btn btn-primary">
					</div>
				</form>
				
					
			</div>
		</div>
</nav>




<table style="width: 100%; float: left; top: 14%" class="table table-striped table-hover">
	  <thead>
	    <tr>
	    
	      <th scope="col">IP</th>
	      <th scope="col">Hostname</th>
	      <th scope="col">MAC</th>
	      <th scope="col">Объект</th>
	      <th scope="col">Устройство</th>
	    </tr>
	  </thead>
	  <tbody>
	
	  	{% for device in listDevice %}
	  	
	    <tr>
	 
	      <td>{{device.0}}</td>
	      <td>{{device.2}}</td>
	      <td>{{device.1}}</td>
	      <td>{{device.4}}</td>
	      {% if device.3 == "Телефонная База" or  device.3 == "Принтер" %}
	      <td><a style="cursor: pointer;" target="_blank" href="http:\\{{device.0}}">{{device.3}}</a></td>
	      {% else %}
	      <td>{{device.3}}</td>

	      {% endif %}
	    </tr>
	 
	   	{% endfor %}
	  </tbody>
</table>




{% endblock %}